"""add promo_code tables at. 2

Revision ID: 748a335720c0
Revises: 5d6883e8d864
Create Date: 2025-07-09 22:11:31.018032

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '748a335720c0'
down_revision = '5d6883e8d864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('discount_percent', 'discount_fixed', 'free_days', name='promo_code_type'), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Скидка в %'),
    sa.Column('discount_amt', sa.Numeric(precision=10, scale=2), nullable=True, comment='Фиксированная скидка в ₽'),
    sa.Column('free_days', sa.Integer(), nullable=True, comment='Бесплатные дни'),
    sa.Column('valid_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True, comment='Дата истечения'),
    sa.Column('usage_limit', sa.Integer(), nullable=True, comment='Лимит использований, NULL = нет'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_promo_code')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
