"""Rename tz_name to tz_offset

Revision ID: a5e285fd4608
Revises: 727e919e6a3d
Create Date: 2025-07-08 01:38:44.687157

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5e285fd4608'
down_revision = '727e919e6a3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tz_offset', sa.SmallInteger(), nullable=False))
    op.drop_column('user', 'tz_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tz_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user', 'tz_offset')
    # ### end Alembic commands ###
